version: "3"
services:
    ui:
        container_name: chat-ui
        build:
            context: ./ui/
        command: yarn start
        ports:
            - "3000:3000"
        volumes:
            - ./ui:/usr/app
        environment:
          - NODE_ENV=development
          - CHOKIDAR_USEPOLLING=true
    api:
        container_name: chat-api
        build:
            context: ./server/
        ports:
            - "8080:8080"
        volumes:
            - ./server:/usr/app
        links:
            - redis
        environment:
            - REDIS_URL=redis://cache
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
    redis:
        image: redis
        container_name: cache
        expose:
            - 6379
